language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql
  
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - mysql -u root -e 'create database DevTv_DB;'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - composer install --dev --prefer-source --no-interaction
  - php artisan migrate --force
  - php artisan db:seed
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - travis_retry php vendor/bin/coveralls -v

notifications:
   slack: red-creek:bXLrIwXudNv0Jpi7pDtvjmNM
